# example values
server:
  port: 8080

spring:
  datasource:
    username: root
    password: cnhtktw1230
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

indexing-settings:
  sites:
    - url: https://et-cetera.ru/mobile/
      name: Et-cetera-mobile
    - url: https://www.svetlovka.ru/
      name: Светловка
#    - url: https://www.lutherancathedral.ru/
#      name: Собор
#    - url: https://www.lenta.ru
#      name: Лента.ру
#    - url: https://www.skillbox.ru
#      name: Skillbox
#    - url: https://www.playback.ru
#      name: PlayBack.Ru
